### PR TITLE
Support for custom ids.

### PR DESCRIPTION
**Pull request by seuros**

### CODE REVIEW

**Comment by dhh** [comment]
I don't think this is necessary. For Active Record, the code is:

``` ruby
      def id
        sync_with_transaction_state
        read_attribute(self.class.primary_key)
      end
```

So the primary key is accessible through the #id method -- regardless of what it's called.

**Comment by seuros** [comment]
Why closed ? 
what about activemodels ?

**Comment by dhh** [comment]
Active Model doesn't have any concept of #primary_key. Everyhing is just run off #id. I think it's best we stick to that.

**Comment by seuros** [comment]
ok

**Pull request closed without merging**
