### PR TITLE
Moves regexp to a constant. I find this improves

### PR DESCRIPTION
**Pull request by andyatkinson**
code readability. Adds a couple valid 
and invalid regexp test assertions.

Adds tests for the locate_signed method in 
GlobalLocator that match the "locate" method tests, 
but with a SignedGlobalID object.

### CODE REVIEW

**Comment by dhh** [comment]
I don't like the move of the regexp to the constant. That actually hurts readability to me.

But thanks for adding the sgid tests. Let's put them in their own class, though.

**Comment by rafaelfranca** [comment]
Yes. Agree about the constant.

**Comment by andyatkinson** [comment]
Ok,  no problem. I moved the tests to a new class. I noticed that a `ActiveSupport::MessageVerifier::InvalidSignature` is raised in the test where a invalid sgid is passed to the initializer. I wasn't sure if raising the exception was desired behavior, or returning nil. I left the test in and made it assert that the exception was raised. Feel free to change it. Thanks.

**Comment by rafaelfranca** [comment]
There are some tests on the old file already. Could you move they too?

**Comment by andyatkinson** [comment]
Removed them from the previous spot and force pushed. I guess another person wrote the same tests around the same time!

**Comment by rafaelfranca** [comment]
Yes, think so. @dhh looks good to me.

**Pull request merged**
