### PR TITLE
require rails/railtie first

### PR DESCRIPTION
**Pull request by chetan**
Was getting the following error when trying to load the gem:

```
.../lib/active_model/global_identification.rb:6:in `<module:GlobalIdentification>': uninitialized constant ActiveSupport::Concern (NameError)
  from .../lib/active_model/global_identification.rb:5:in `<module:ActiveModel>'
  from .../lib/active_model/global_identification.rb:4:in `<top (required)>'
  from .../lib/active_model/railtie.rb:3:in `require'
  from .../lib/active_model/railtie.rb:3:in `<top (required)>'
  from .../config/application.rb:4:in `require'
  from .../config/application.rb:4:in `<top (required)>'
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
hmm, I think it is because the railtie definition is reopening the `ActiveModel::Railtie`. Could you change your PR to define a `ActiveModel::GlobalIdentification::Railtie`?

**Comment by chetan** [comment]
Just tried that but I still get the same error as above

**Comment by rafaelfranca** [comment]
When loading this gem Rails should be already loaded so there is no need to load it again. We need to understand why in your case it is not to do a proper fix.

**Comment by chetan** [comment]
Yeah, I figured there might be something screwy going on. I checked my config/application.rb against the latest generator files and it looks ok (rails 4.1.1 fwiw). 

All the same, imho, "xyz should have been loaded at this point" is a bit of a copout -- best to be explicit about dependencies and not assume some particular usage.

**Comment by rafaelfranca** [comment]
Yes, not saying we should not define the dependency but I guess there is something deeper causing this that need to be fixed too, for example this gem reopening the ActiveModel::Railtie (it should not)

**Comment by chetan** [comment]
Agree with changing the name of the class; it should be properly namespaced. I can open up a separate PR for that

**Comment by rafaelfranca** [comment]
:+1:

**Pull request merged**
